//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.FamilyShowLib.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.FamilyShowLib.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Info.
        /// </summary>
        public static string AdditionalInfo {
            get {
                return ResourceManager.GetString("AdditionalInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new person as.
        /// </summary>
        public static string AddNewPersonAs {
            get {
                return ResourceManager.GetString("AddNewPersonAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adopted.
        /// </summary>
        public static string Adopted {
            get {
                return ResourceManager.GetString("Adopted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age.
        /// </summary>
        public static string Age {
            get {
                return ResourceManager.GetString("Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ancestral generations:.
        /// </summary>
        public static string AncestralGenerations {
            get {
                return ResourceManager.GetString("AncestralGenerations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and.
        /// </summary>
        public static string And {
            get {
                return ResourceManager.GetString("And", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to at.
        /// </summary>
        public static string At {
            get {
                return ResourceManager.GetString("At", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        public static string Author {
            get {
                return ResourceManager.GetString("Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birth Date.
        /// </summary>
        public static string BirthDate {
            get {
                return ResourceManager.GetString("BirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birth Place.
        /// </summary>
        public static string BirthPlace {
            get {
                return ResourceManager.GetString("BirthPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Births.
        /// </summary>
        public static string Births {
            get {
                return ResourceManager.GetString("Births", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brother.
        /// </summary>
        public static string Brother {
            get {
                return ResourceManager.GetString("Brother", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Burial Date.
        /// </summary>
        public static string BurialDate {
            get {
                return ResourceManager.GetString("BurialDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Burial Place.
        /// </summary>
        public static string BurialPlace {
            get {
                return ResourceManager.GetString("BurialPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Burials.
        /// </summary>
        public static string Burials {
            get {
                return ResourceManager.GetString("Burials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Child.
        /// </summary>
        public static string Child {
            get {
                return ResourceManager.GetString("Child", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compatability.
        /// </summary>
        public static string Compatability {
            get {
                return ResourceManager.GetString("Compatability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This file was created with an earlier version of Family.Show.  Family.Show Version 4 has many new features which allow you to record additional information about your family.  Please note that you may lose data if you edit a file created in a newer version of Family.Show with an earlier version of the program..
        /// </summary>
        public static string CompatabilityMessage {
            get {
                return ResourceManager.GetString("CompatabilityMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cremation Date.
        /// </summary>
        public static string CremationDate {
            get {
                return ResourceManager.GetString("CremationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cremation Place.
        /// </summary>
        public static string CremationPlace {
            get {
                return ResourceManager.GetString("CremationPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cremations.
        /// </summary>
        public static string Cremations {
            get {
                return ResourceManager.GetString("Cremations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current person:.
        /// </summary>
        public static string CurrentPerson {
            get {
                return ResourceManager.GetString("CurrentPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daughter.
        /// </summary>
        public static string Daughter {
            get {
                return ResourceManager.GetString("Daughter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Death Date.
        /// </summary>
        public static string DeathDate {
            get {
                return ResourceManager.GetString("DeathDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Death Place.
        /// </summary>
        public static string DeathPlace {
            get {
                return ResourceManager.GetString("DeathPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deaths.
        /// </summary>
        public static string Deaths {
            get {
                return ResourceManager.GetString("Deaths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descendant generations:.
        /// </summary>
        public static string DescendantGenerations {
            get {
                return ResourceManager.GetString("DescendantGenerations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to died on.
        /// </summary>
        public static string DiedOn {
            get {
                return ResourceManager.GetString("DiedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate people:.
        /// </summary>
        public static string DuplicatePeople {
            get {
                return ResourceManager.GetString("DuplicatePeople", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Education.
        /// </summary>
        public static string Education {
            get {
                return ResourceManager.GetString("Education", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events.
        /// </summary>
        public static string Events {
            get {
                return ResourceManager.GetString("Events", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Family.Show.
        /// </summary>
        public static string FamilyShow {
            get {
                return ResourceManager.GetString("FamilyShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Family Tree.
        /// </summary>
        public static string FamilyTree {
            get {
                return ResourceManager.GetString("FamilyTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Father.
        /// </summary>
        public static string Father {
            get {
                return ResourceManager.GetString("Father", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtered on:.
        /// </summary>
        public static string FilteredOn {
            get {
                return ResourceManager.GetString("FilteredOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foster.
        /// </summary>
        public static string Foster {
            get {
                return ResourceManager.GetString("Foster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generated by Family.Show Version.
        /// </summary>
        public static string GeneratedByFamilyShow {
            get {
                return ResourceManager.GetString("GeneratedByFamilyShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide all notes.
        /// </summary>
        public static string HideNotes {
            get {
                return ResourceManager.GetString("HideNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiding notes requires JavaScript to be enabled..
        /// </summary>
        public static string HidingNotes {
            get {
                return ResourceManager.GetString("HidingNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Husband.
        /// </summary>
        public static string Husband {
            get {
                return ResourceManager.GetString("Husband", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imported people:.
        /// </summary>
        public static string ImportedPeople {
            get {
                return ResourceManager.GetString("ImportedPeople", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imported Repositories:.
        /// </summary>
        public static string ImportedRepositories {
            get {
                return ResourceManager.GetString("ImportedRepositories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imported Sources:.
        /// </summary>
        public static string ImportedSources {
            get {
                return ResourceManager.GetString("ImportedSources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in.
        /// </summary>
        public static string In {
            get {
                return ResourceManager.GetString("In", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This does not appear to be a valid date (DD/MM/YYYY)..
        /// </summary>
        public static string InvalidDate {
            get {
                return ResourceManager.GetString("InvalidDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Living.
        /// </summary>
        public static string Living {
            get {
                return ResourceManager.GetString("Living", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marriages.
        /// </summary>
        public static string Marriages {
            get {
                return ResourceManager.GetString("Marriages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merged repositories:.
        /// </summary>
        public static string MergedRepositories {
            get {
                return ResourceManager.GetString("MergedRepositories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merged sources:.
        /// </summary>
        public static string MergedSources {
            get {
                return ResourceManager.GetString("MergedSources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mother.
        /// </summary>
        public static string Mother {
            get {
                return ResourceManager.GetString("Mother", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name(s).
        /// </summary>
        public static string Names {
            get {
                return ResourceManager.GetString("Names", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Natural.
        /// </summary>
        public static string Natural {
            get {
                return ResourceManager.GetString("Natural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No places to export..
        /// </summary>
        public static string NoPlaces {
            get {
                return ResourceManager.GetString("NoPlaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No repositories to import..
        /// </summary>
        public static string NoRepositories {
            get {
                return ResourceManager.GetString("NoRepositories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No sources to import..
        /// </summary>
        public static string NoSources {
            get {
                return ResourceManager.GetString("NoSources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        public static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of people:.
        /// </summary>
        public static string NumberOfPeople {
            get {
                return ResourceManager.GetString("NumberOfPeople", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occupation.
        /// </summary>
        public static string Occupation {
            get {
                return ResourceManager.GetString("Occupation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of.
        /// </summary>
        public static string Of {
            get {
                return ResourceManager.GetString("Of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to on.
        /// </summary>
        public static string On {
            get {
                return ResourceManager.GetString("On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent.
        /// </summary>
        public static string Parent {
            get {
                return ResourceManager.GetString("Parent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to People.
        /// </summary>
        public static string People {
            get {
                return ResourceManager.GetString("People", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to people imported..
        /// </summary>
        public static string PeopleImported {
            get {
                return ResourceManager.GetString("PeopleImported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to places exported..
        /// </summary>
        public static string PlacesExported {
            get {
                return ResourceManager.GetString("PlacesExported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private Record.
        /// </summary>
        public static string PrivateRecord {
            get {
                return ResourceManager.GetString("PrivateRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publisher.
        /// </summary>
        public static string Publisher {
            get {
                return ResourceManager.GetString("Publisher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relationship to Current Person.
        /// </summary>
        public static string RelationshipToCurrentPerson {
            get {
                return ResourceManager.GetString("RelationshipToCurrentPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Religion.
        /// </summary>
        public static string Religion {
            get {
                return ResourceManager.GetString("Religion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to repositories imported..
        /// </summary>
        public static string RepositoriesImported {
            get {
                return ResourceManager.GetString("RepositoriesImported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repository.
        /// </summary>
        public static string Repository {
            get {
                return ResourceManager.GetString("Repository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show all notes.
        /// </summary>
        public static string ShowNotes {
            get {
                return ResourceManager.GetString("ShowNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sibling.
        /// </summary>
        public static string Sibling {
            get {
                return ResourceManager.GetString("Sibling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sister.
        /// </summary>
        public static string Sister {
            get {
                return ResourceManager.GetString("Sister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Son.
        /// </summary>
        public static string Son {
            get {
                return ResourceManager.GetString("Son", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        public static string Source {
            get {
                return ResourceManager.GetString("Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sources imported..
        /// </summary>
        public static string SourcesImported {
            get {
                return ResourceManager.GetString("SourcesImported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spouse.
        /// </summary>
        public static string Spouse {
            get {
                return ResourceManager.GetString("Spouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary of people.
        /// </summary>
        public static string SummaryOfPeople {
            get {
                return ResourceManager.GetString("SummaryOfPeople", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary of reporitories.
        /// </summary>
        public static string SummaryOfRepositories {
            get {
                return ResourceManager.GetString("SummaryOfRepositories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary of repositories for file.
        /// </summary>
        public static string SummaryOfRepositoriesForFile {
            get {
                return ResourceManager.GetString("SummaryOfRepositoriesForFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary of sources.
        /// </summary>
        public static string SummaryOfSources {
            get {
                return ResourceManager.GetString("SummaryOfSources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary of sources for file.
        /// </summary>
        public static string SummaryOfSourcesForFile {
            get {
                return ResourceManager.GetString("SummaryOfSourcesForFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surname.
        /// </summary>
        public static string Surname {
            get {
                return ResourceManager.GetString("Surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to.
        /// </summary>
        public static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to was born on.
        /// </summary>
        public static string WasBornOn {
            get {
                return ResourceManager.GetString("WasBornOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to was buried on.
        /// </summary>
        public static string WasBuriedOn {
            get {
                return ResourceManager.GetString("WasBuriedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to was cremated on.
        /// </summary>
        public static string WasCrematedOn {
            get {
                return ResourceManager.GetString("WasCrematedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wife.
        /// </summary>
        public static string Wife {
            get {
                return ResourceManager.GetString("Wife", resourceCulture);
            }
        }
    }
}
