//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.312
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.FamilyShow.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.FamilyShow.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *.*.
        /// </summary>
        internal static string AllExtension {
            get {
                return ResourceManager.GetString("AllExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Files (*.*).
        /// </summary>
        internal static string AllFiles {
            get {
                return ResourceManager.GetString("AllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .family.
        /// </summary>
        internal static string DefaultFamilyExtension {
            get {
                return ResourceManager.GetString("DefaultFamilyExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .ged.
        /// </summary>
        internal static string DefaultGedcomExtension {
            get {
                return ResourceManager.GetString("DefaultGedcomExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Nullam in lorem ut ante iaculis dictum. Maecenas suscipit velit at diam. Cras ac enim. Curabitur neque erat, faucibus in, tempus at, consequat non, turpis. Aliquam erat volutpat. Nunc ligula metus, semper ac, ultricies at, commodo molestie, nisl. Morbi felis elit, feugiat et, volutpat nec, vulputate vitae, dolor. Nam mauris nulla, adipiscing sodales, pulvinar in, sodales vitae, odio. Sed eu pede. Vivamus ac augue id felis porta bibendum. Sed sapien o [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DefaultStory {
            get {
                return ResourceManager.GetString("DefaultStory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .xps.
        /// </summary>
        internal static string DefaultXpsExtension {
            get {
                return ResourceManager.GetString("DefaultXpsExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        internal static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *.family.
        /// </summary>
        internal static string FamilyExtension {
            get {
                return ResourceManager.GetString("FamilyExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Family.Show Files (.family).
        /// </summary>
        internal static string FamilyFiles {
            get {
                return ResourceManager.GetString("FamilyFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *.ged.
        /// </summary>
        internal static string GedcomExtension {
            get {
                return ResourceManager.GetString("GedcomExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Failed.
        /// </summary>
        internal static string GedcomFailed {
            get {
                return ResourceManager.GetString("GedcomFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The GEDCOM file could not be imported..
        /// </summary>
        internal static string GedcomFailedMessage {
            get {
                return ResourceManager.GetString("GedcomFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gedcom Files (.ged).
        /// </summary>
        internal static string GedcomFiles {
            get {
                return ResourceManager.GetString("GedcomFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        internal static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *.jpg.
        /// </summary>
        internal static string JpegExtension {
            get {
                return ResourceManager.GetString("JpegExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Family.Show Files (.jpg).
        /// </summary>
        internal static string JpegFiles {
            get {
                return ResourceManager.GetString("JpegFiles", resourceCulture);
            }
        }
        
        internal static byte[] KennedySampleFile {
            get {
                object obj = ResourceManager.GetObject("KennedySampleFile", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The method or operation is not implemented..
        /// </summary>
        internal static string NotImplemented {
            get {
                return ResourceManager.GetString("NotImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string NotSaved {
            get {
                return ResourceManager.GetString("NotSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current family has not been saved. Do you want to save?.
        /// </summary>
        internal static string NotSavedMessage {
            get {
                return ResourceManager.GetString("NotSavedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *.png.
        /// </summary>
        internal static string PngExtension {
            get {
                return ResourceManager.GetString("PngExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Family.Show Files (.png).
        /// </summary>
        internal static string PngFiles {
            get {
                return ResourceManager.GetString("PngFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save As.
        /// </summary>
        internal static string SaveAs {
            get {
                return ResourceManager.GetString("SaveAs", resourceCulture);
            }
        }
        
        internal static byte[] WindsorSampleFile {
            get {
                object obj = ResourceManager.GetObject("WindsorSampleFile", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *.xps.
        /// </summary>
        internal static string XpsExtension {
            get {
                return ResourceManager.GetString("XpsExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xps Files (.xps).
        /// </summary>
        internal static string XpsFiles {
            get {
                return ResourceManager.GetString("XpsFiles", resourceCulture);
            }
        }
    }
}
